In [2]:
# Neighbour Wind Turbine Points
import numpy as np

# Define the grid size
rows, cols = 6, 10  # Adjust according to the grid size in the image

# Create a grid with wind turbine positions (1 represents a turbine)
grid = np.ones((rows, cols), dtype=int)
print(grid)

# Define the function to count neighbors
def count_neighbors(grid, max_distance=2):
    neighbor_counts = np.zeros_like(grid)  # Initialize an array for neighbor counts
    for i in range(grid.shape[0]):
        for j in range(grid.shape[1]):
            if grid[i, j] == 1:  # Only consider cells with a turbine
                count = 0
                # Iterate through possible neighbors within max_distance
                for x in range(max(0, i - max_distance), min(rows, i + max_distance + 1)):
                    for y in range(max(0, j - max_distance), min(cols, j + max_distance + 1)):
                        if (x != i or y != j) and grid[x, y] == 1:
                            # Count as a neighbor if it's within max_distance and not the same cell
                            count += 1
                neighbor_counts[i, j] = count
    return neighbor_counts

# Run the function and print the results
neighbor_counts = count_neighbors(grid)
print("Grid with neighbor counts:")
print(neighbor_counts)


[[1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]]
Grid with neighbor counts:
[[ 8 11 14 14 14 14 14 14 11  8]
 [11 15 19 19 19 19 19 19 15 11]
 [14 19 24 24 24 24 24 24 19 14]
 [14 19 24 24 24 24 24 24 19 14]
 [11 15 19 19 19 19 19 19 15 11]
 [ 8 11 14 14 14 14 14 14 11  8]]
